### ISSUE TITLE
Start Debugging (Launch Browser) not showing

### ISSUE THREAD

**Issue by guilhermecvm** [martomo/SublimeTextXdebug#117]
Hello,

The Start Debugging (Launch Browser) option is not showing on the menu. It worked before (2 weeks ago), nothing was changed in the project.

I already tried to change the url setting on .sublime-project and Xdebug.sublime-settings, but it didn`t work.

**Comment by vmoscolini** [comment]
Just remove the current .sublime-project file and save the project again.

Project -> Save Project As...

Then insert again in the .sublime-project file the code below:

    {
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "."
        }
    ],
    "settings": {
        "xdebug": {
             "url": "http://my.local.website/",
        }
    }
    }

** Be sure to change the "url" to your site base URL.
