### ISSUE TITLE
path_mapping does not support raw network paths in Windows (Samba)

### ISSUE THREAD

**Issue by avindra** [martomo/SublimeTextXdebug#130]
This is an issue:

```
"path_mapping": {
    "/app/myapp/ui" : "\\\\myserver\\\\sambashare\\\\ui"
},
```

That path mapping does not work. And here is the workaround: mount your folder to a share with a drive letter:

```
"path_mapping": {
    "/app/myapp/ui" : "D:/ui"
},
```

Would it be difficult to add native support for un-mounted paths?

**Comment by zephster** [comment]
Apply the patch [in this pull request](https://github.com/martomo/SublimeTextXdebug/pull/119), that made UNC paths work for me.

Weird, though, that mounting the share to a drive letter works for you - it doesn't for me, and the only thing that did work was applying that patch and using the UNC path.

**Comment by avindra** [comment]
@zephster  thanks, that pr https://github.com/martomo/SublimeTextXdebug/pull/119 looks like it does it.

seems a fork is underway https://github.com/ryanpcmcquen/SublimeTextXdebugPlus as the maintainer hasnt responded here
