### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by sameernyaupane** [martomo/SublimeTextXdebug#160]
The plugin doesn't seem to work at all most of the times. It works sometimes with the chrome plugin, but not always.

I see no updates from the plugin author or replies to issues lately.

Is the plugin dead? I wish we had a good xdebug plugin for sublime. Atom's xdebug plugin has much more frequent updates and is active. 

Any thoughts? I understand that martomo might be busy and this is updated in free time. But this is a crucial tool for any php dev. I wish I had some python skills to keep this updated. Unfortunately I don't. Maybe someone else with the skills can get this forked and updated?

Regards

**Comment by DeanBDean** [comment]
I use it almost everyday, and it works fine for me 98% of the time. I don't try to use it in conjunction with a Chrome plugin though

**Comment by sameernyaupane** [comment]
Thanks for the input @DeanBDean . I can't get it to work without chrome plugin anymore. It used to work with previous ver of sublime, but not the recent one. Glad its working for you though.

**Comment by ekosynth** [comment]
If you can learn PHP, you can learn Python!

**Comment by nbyloff** [comment]
I could only use this plugin with the Chrome extension, but now as of the newest version of Sublime Text 3, whenever I turn on debugging, it locks up and crashes ST. So I can't use it at all anymore.

**Comment by sameernyaupane** [comment]
@ekosynth Can't argue with that. ;) I might as well start messing with Python.

@nbyloff same here. I like Sublime for PHP a lot, the only thing missing in it is a proper Xdebug plugin. I hope the author finds some time to work on it again. Or somebody else forks it out and updates it.

**Comment by JeremyHargis** [comment]
@sameernyaupane Which versions of Sublime, PHP, and xdebug are you using? Which OS are on you? I'm using the latest Sublime build and PHP7 on Linux and this seems to be working perfectly in Chrome with no extensions required. In my testing, I am setting breakpoints and it seems to work as you would expect.

**Comment by alextselegidis** [comment]
I also having problems with the plugin (crashing) with ST3 (build 3114) under Ubuntu 14.04 & PHP 5.5.

**Comment by tchalvak** [comment]
I am also have the issue of near constant crashing of the plugin, while using Sublime Text 3 (build 3114), and Xdebug Client.
Running OS Ubuntu 14.04.

**Comment by RodrigoSaka** [comment]
I'm very sad, most of the sublime plugins are dead!
Sublime text is very quick to compare with another text editor, but I feel that the sublime is abandoned.
I'm forced to switch to another text editor.

**Comment by sameernyaupane** [comment]
@RodrigoSaka , I've long switched to PHPStorm. Try it out, it is amazing. Has Xdebug, PHPUnit all built in.

**Comment by tchalvak** [comment]
@RodrigoSaka  Sublime is definitely alive and well, though as time goes on and sublime versions change, older and more complicated sublime plugins will tend to degrade or be left behind.  My advice these days is indeed to use/abuse the free-trial of PHPStorm to get xdebug working there.  If you can get it working there, you have a much better chance of piggybacking on that working approach and trying to get the sublime xdebug plugin working as well.  But in the end, Sublime isn't meant as an IDE for php specifically, but just a primo & fast coding editor instead, so the plugin might not be enough.

**Comment by ekosynth** [comment]
+1 @sameernyaupane and @tchalvak 

I switched to PHPStorm and found it generally much better for PHP. I still go back to Sublime when I need a really efficient notepad, with a lot of flexibility to manipulate text.

**Comment by RodrigoSaka** [comment]
@tchalvak 
I fully agree with what you said, really the subblime was not meant to be an IDE but I like this installation flexibility and varieties of plugins.
No doubt the PHPStorm is great for the development, I look for something that is less expensive.
I've tried using vscode and atom but unfortunately their performance is horrible, vscode still performs reasonably.

**Comment by marcus-at-localhorst** [comment]
STXdebug fails me as well most of the time. I found a relatively lightweight alternative in Pugdebug https://github.com/robertbasic/pugdebug

**Comment by nbyloff** [comment]
I am going to take a look at pugdebug, but was hoping this actual plugin would continue and become more stable. This version is officially dead; the developer hasn't made a commit or communicated with anyone in over 3 years and there are a lot of pull requests that have gone ignored. While it still works for the most part, it's still pretty buggy and will eventually stop working as ST gets updated.  

I don't know enough about XDebug to create a new official fork, but will take a look to see if there's enough documentation out there to make it worth while. I haven't used PHPStorm in a while, but I prefer ST because of how light weight it is.

**Comment by mrphang** [comment]
One of my commits was just commented on a couple days ago, so maybe not so dead?? I use this extension everyday at work.

**Comment by martomo** [comment]
I've picked up development of this plugin, now that I have some time, current goal is to release an update in the next couple days, addressing some of the reported/outstanding issues, requested features, syntax definition improvements and more...
After that I have no concrete plans (yet), but I would like to focus on the connectivity issues you all have been experiencing as that is currently a big mess, looking back upon this old code.
