### ISSUE TITLE
cli example

### ISSUE THREAD

**Issue by mshallop** [martomo/SublimeTextXdebug#178]
Can you add a cli example to the readme?

**Comment by martomo** [comment]
This is already in README, please see the __[How can I start a debugging session?](https://github.com/martomo/SublimeTextXdebug#how-can-i-start-a-debugging-session)__ section.

> If you want to run a start a debugging session from command line, before you run your script, you will need to set the environment variable __XDEBUG_CONFIG__ with the IDE key.
> 
> __Windows__
> ```
> set XDEBUG_CONFIG="idekey=sublime.xdebug"
> php myscript.php
> ```
> __UNIX__
> ```
> export XDEBUG_CONFIG="idekey=sublime.xdebug"
> php myscript.php
> ```
