### ISSUE TITLE
Python error line 244 -- TypeError: an integer is required (got type str)

### ISSUE THREAD

**Issue by matty235** [martomo/SublimeTextXdebug#179]
Here's info from the log file.

Exception in thread Thread-9:
Traceback (most recent call last):
  File "xdebug.protocol in /home/chewie/.config/sublime-text-3/Installed Packages/Xdebug Client.sublime-package", line 244, in listen
TypeError: an integer is required (got type str)

I can't tell what's on line 244, the package is a binary.

What other information can I provide to be useful for you?

**Comment by martomo** [comment]
@matty235 If possible please provide other information as described in the [**README**](https://github.com/martomo/SublimeTextXdebug#what-to-do-when-you-experience-any-issues).

**Comment by martomo** [comment]
@matty235 I managed to reproduce the exception, it seems to happen when you specify `port` in configuration as string, when in fact it should be an integer.
In case you are still experiencing this issue please double check your configuration.
