### ISSUE TITLE
ST3 doesn't stop at breakpoints neither show debug info

### ISSUE THREAD

**Issue by megusta420** [martomo/SublimeTextXdebug#180]
Hello and thank you for your work!

I am using Windows 10 as host system and Vagrant (Ubuntu) as guest OS.
My editor is ST3 and I've installed XDebug plugin (upgraded to the latest version).
Also I've successfully installed xdebug on Vagrant OS:

![phpinfo](https://user-images.githubusercontent.com/28196153/35585523-d1d9bbf8-0600-11e8-899a-009dc7b6f422.png)
with the next config:

![image](https://user-images.githubusercontent.com/28196153/35585559-ef294980-0600-11e8-82b4-4401e6d5506d.png)

Also here is my ST3 xdebug config:

![image](https://user-images.githubusercontent.com/28196153/35585582-04c48796-0601-11e8-9e95-3336a928017d.png)

This is netstat on W10 host which shows that port is binded with plugin:

![image](https://user-images.githubusercontent.com/28196153/35585628-24a94e34-0601-11e8-8bc3-cf4d28360db5.png)

And this is the screenshot which shows xdebug log file on vagrant:

![image](https://user-images.githubusercontent.com/28196153/35585677-4d31f98c-0601-11e8-8c87-64adcde4ad4d.png)

This is what happened when the new tab opened after running xdebug session:

![image](https://user-images.githubusercontent.com/28196153/35585704-5eb160bc-0601-11e8-9704-738af92c2def.png)

And this is what happened (as you see nothing) in ST3:

![image](https://user-images.githubusercontent.com/28196153/35585732-7078676e-0601-11e8-97d9-9bd20ea22135.png)

And this is the ST3 console output:

![image](https://user-images.githubusercontent.com/28196153/35585830-ae1b0446-0601-11e8-9ab3-8f8cec603ca7.png)

So, tell me please, what am I doing wrong?

**Comment by megusta420** [comment]
OOops! It was my mistake, I inserted port and other settings as a nested array into the "path_mapping" :( Sorry for disturbance, got it working as expected.

**Comment by martomo** [comment]
Glad to hear you got it working, will close the issue in order to mark it as resolved.
