### ISSUE TITLE
Inspecting variables in context opens window-ish?

### ISSUE THREAD

**Issue by Jarvvski** [martomo/SublimeTextXdebug#183]
I don't think this is a bug, but unsure where to ask.

When I try to 'unfurl' an array variable in the context, it opens it beneath in some kind of text box:

![screen shot 2018-04-03 at 15 21 45](https://user-images.githubusercontent.com/6012840/38255187-10899f48-3753-11e8-8349-354abd5affda.png)

Any ideas? I'm sure it used to open inside the context window in the past

**Comment by martomo** [comment]
When you click on the variable in the Context view, it will show the variable (and it's children) in the output panel.
What you are referring to, is the Fold/Unfold functionality, when you click on the arrow in the gutter, to the left of the variable (with children) in the Context view, it will expand the variable showing it's children.

**Comment by martomo** [comment]
@Jarvvski There is currently no option available to print content unfolded in the Context view, as the intended usage is to show selected variable (and it's children) in the output panel with the simple click.
Alternatively you can unfold all the content in Context view with a single operation through Sublime text menu (__Edit > Code Folding > Unfold All__) or using it's corresponding shortcut as shown in the menu.

**Comment by Jarvvski** [comment]
sorry for not getting back to you @martomo. All good on my end now
