### ISSUE TITLE
Breakpoints not hit

### ISSUE THREAD

**Issue by g105b** [martomo/SublimeTextXdebug#2]
I bet you're sick of hearing from me :)

I have followed your installation instructions for yesterday's update, but nothing I try makes breakpoints get hit. The context and stack windows remain empty, but the following message is displayed in the status bar every time I refresh the page:

![image](https://f.cloud.github.com/assets/358014/708541/976508e0-de48-11e2-9501-f67eb0d57613.png)

This is with or without `?XDEBUG_SESSION_START=sublime.xdebug`, restarted webserver, double-checked php.ini... I can't think of anything else, please advise.

**Comment by mjquito** [comment]
I need help, everything is working fine except my breakpoints. The xdebug_content and stack are showing the stuff, but when I debug a file, i can't see which break-point is being debugged. This problem is similar to @stridera. My sublime is on a windows 7, the server (LAMP) is localhost. 

{
	"folders":
	[
		{
			"path": "\\\\ubuntu\\local.martinquito.mjquito.com"
		}
	],
    "settings": {
        "xdebug": {
        	"path_mapping": {
	        	"/opt/bitnami/apache2/htdocs/" : "\\\\ubuntu\\local.martinquito.mjquito.com"
	   		},
        	"port": 9000, 
        }
    }
}

**Comment by ramanacv** [comment]
Hi Martomo
I am using sublime3 and its built in xdebug plugin. The zf2 application code stepping happens only in the initial bootstrapping module but doesnt stop in controllers. 
Any reason why this could be ? 
I also see client connection timeout errors in xdebug-debug.log file
thanks

**Comment by ramanacv** [comment]
{
	"folders":
	[
		{
			"path": "C:\\xampp\\htdocs\\myrpoj",
			"follow_symlinks" : true, 
		}
	], 

	"settings" : 
		{
			 "xdebug": 
			 {
			
				"path_mapping" :  { "C:\\xampp\\htdocs\\myproj" : "D:\\work\\projects\\myproj" },
			"url" : "http://myproj.localhost/",
			"super_globals": true,
            "close_on_stop": true
			}
		}
}

**Comment by rogerywoo** [comment]
I was having the same problem.  The application was breaking in the breakpoint, but the little yellow arrow as not being displayed.  After working on it for several hours, Martomo comment on path_mapping gave me an idea.  The path mapping is CASE SENSITIVE.  I had /home/vagrant/PhpProject/.  The folder in the virtualbox was phpproject.
