### ISSUE TITLE
Using GitGutter, breakpoints show in gutter but not debug session line marker/pointer

### ISSUE THREAD

**Issue by robrecord** [martomo/SublimeTextXdebug#33]
I have GitGutter installed.

In terms of the gutter markers, it seems to play nice with sublime-lint, and Xdebug breakpoints.

Xdebug line markers when debugging however, are not shown (the GitGutter markers seem to take precedence).

Is there anything that can be done? When debugging I don't care about the GitGutter markers - only when editing, so I'd rather Xdebug markers take precedence.

Thanks!

**Comment by wprater** [comment]
any hope here?  Im having the same issue.  are there workarounds we can look to use? this seems relevant as well https://github.com/jisaacks/GitGutter/issues/113
