### ISSUE TITLE
Would love to be able to re-map Fn keys in user prefs.

### ISSUE THREAD

**Issue by dtrenz** [martomo/SublimeTextXdebug#38]
I like using my iTunes media controls on my mack keyboard (F7-F12), but I have extra Fn keys that are not in use (F13-F19) nthat I would prefer to map to Step In/Over/Out type controls.

**Comment by mokanfar** [comment]
I would also like to point out that the function key representations in sublime text user keymap file are case sensitive. Uppercase "F19" will not work it has to be lower case "f19".
