### ISSUE TITLE
Ajax call doesn't trigger breakpoint

### ISSUE THREAD

**Issue by webpolis** [martomo/SublimeTextXdebug#65]
I have successfully configured sublime and xdebug, as "break_on_start" will trigger the proper call in sublime.

But, when from my app (Laravel PHP) i make an ajax call like: "http://pe.localhost/projects", and I have a breakpoint in ProjectsController.php where that particular URL/action is defined, the breakpoint is never triggered. The HTTP request is sending the proper param name as cookie:

XDEBUG_SESSION: sublime.xdebug

My custom sublime settings are:

  "settings": {
    "xdebug": {
      "url": "http://pe.localhost",
      "super_globals": true,
      "close_on_stop": true
    }
  }

I'm debugging in my localhost (alias pe.localhost).

Any help will be very appreciated.
Thanks.
Nicolas

**Comment by tom808** [comment]
@webpolis possibly the worst thing you want to read on a thread where you are having similar issues.

I can't get AJAX calls to trigger Xdebug either!

**Comment by juanmiguel431** [comment]
Thanks @martomo.

It worked for me your suggestion. I added the XDEBUG_SESSION_START to the parameter request and works. :)
```
	conexion.open('POST', 'c9-1.php', true);
	conexion.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
	var parametes = "pais="+encodeURIComponent(pais.value)+"XDEBUG_SESSION_START="+encodeURIComponent("sublime.xdebug");
	conexion.send(parametes);
```
