### ISSUE TITLE
Nested arrays not displaying in context window

### ISSUE THREAD

**Issue by richardbporter** [martomo/SublimeTextXdebug#66]
I have a similar problem to #59 but with nested arrays. I can expand a top-level array just fine in the xdebug context window but any array nested within that just shows the number of children with an ellipsis. This happens whether I set max_depth, max_children, max_data or not. A manual var_dump() shows everything. Any ideas on this?

Great plugin and thanks for any information you can provide.

Installed from Package Control
Mac OS X 10.9.1
ST2 2.0.2
xdebug 2.1.0

*.sublime-project
...
"max_children": -1, // (or any other sane value)
"max_depth": -1,
"max_data": -1,
...

PHP 5.3.6 INI
...
xdebug.default_enable=1
xdebug.auto_trace=1
xdebug.remote_enable=1
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.remote_handler=dbgp
xdebug.var_display_max_children=-1 // (or any other sane value)
xdebug.var_display_max_depth=-1
xdebug.var_display_max_data=-1

**Comment by chrisgravel** [comment]
I found a solution to this. Please see: https://github.com/martomo/SublimeTextXdebug/issues/128 and let me know if it works. I believe this is a problem with Package Control installation not creating the directory because there is a space in the directory name, "Xdebug Client". If this solution works for you, please comment.

**Comment by sodacrackers** [comment]
Same issue, where I need more detail about a variable in "Xdebug Context."  Is there a way to execute PHP in the active debugger session?  Eg can I `View > Show Console` then `print print_r($_SESSION['some_array']['some_member']);` 

Anyway to see variables better??
