### ISSUE TITLE
Parsing Xdebug Engine's XML Response sometimes fails

### ISSUE THREAD

**Issue by jbeales** [martomo/SublimeTextXdebug#77]
Debugging WordPress issues, sometimes the XML that the Xdebug engine sends back to SublimeTextXdebug isn't valid, so parsing fails.

The invalid XML fragment looks like this:

```
<property name="&#0;lambda_13" fullname="$wp_filter[&#39;widgets_init&#39;][10][&#39;&#0;lambda_13&#39;]" address="4579437104" type="array" children="1" numchildren="2"></property>
```

The problem is the &#0.

This seems to be acknowledged in [Xdebug issue 924](http://bugs.xdebug.org/view.php?id=924), but it seems their "solution" might be to not use XML, if I understand properly. Is there a way we can follow the recommendation?

**Comment by brannou** [comment]
I have the exact same problem with wordpress when I try to use xdebug client. I don't know if it's a dumb suggestion but would it be possible to filter the xml output sent by xdebug before it's shown in client panels ?
