### ISSUE TITLE
Always switches to last tab on "Stop Debugging (Close Windows)" Command

### ISSUE THREAD

**Issue by jambox** [martomo/SublimeTextXdebug#85]
When I'm in the middle of debugging and I use the `Stop Debugging (Close Windows)` command, ST3 always switches to the last tab that's open in my current ST window. If I'm deep into a particular block of code and this happens, it can interrupt my flow pretty hard and I can lose my place or train of thought.

Is it possible to add some code to retain the current active tab in the non-debug window and keep that tab active on close?

Thanks again

**Comment by astasoft** [comment]
@martomo the PR is not merged to the master?
