### ISSUE TITLE
Connects but nothing happens

### ISSUE THREAD

**Issue by numkem** [martomo/SublimeTextXdebug#9]
Hello,

I'm trying to get this package working so I could pretty much ditch my old IDE for pure Sublime Text.

I use this configuration for xdebug:

``` ini
zend_extension=/usr/lib/php/modules/xdebug.so
xdebug.remote_enable=on
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9000
xdebug.remote_handler="dbgp"
xdebug.remote_mode=req
xdebug.idekey=sublime.xdebug
```

And this is configuration for Sublime Text:

``` json
{
    "port": 9000, 
    "close_on_stop": true,
    "max_depth": 3,
    "max_children": 32
}
```

And after adding a breakpoint using the command pallet (I can see the grey dot for the breakpoint) and starting Debugging with the same way, I hit the URL with `XDEBUG_SESSION_START=1` at the end of the URL (I have other params in my URL).

I see the status bar says `Xdebug: Connected` and when checking port `9000` I can really see it's indeed connected:

```
$ netstat -an | grep 9000
tcp        0      0 127.0.0.1:9000          127.0.0.1:52515         ESTABLISHED
tcp        0      0 127.0.0.1:52515         127.0.0.1:9000          ESTABLISHED
```

But than nothing else happens and the request gets stuck in the browser and never reaches the breakpoint.

Is there something I'm missing?

Thanks!

**Comment by aneetkukreja1** [comment]
Check sublime terminal (Ctrl + ~) if it shows error like xdebug xml.etree.ElementTree.ParseError: not well-formed (invalid token) then it is issue of sublime xdebug client installed through sublime package manager.

1. Uninstall xdebug client installed through Package manager
Preferences > Package control > remove package > xdebug client

2. Quit sublime

3. Install client manually through source code
Get fixed source code of xdebug client from 
https://github.com/gepeixoto/SublimeTextXdebug.git
- Download source code (do not follow install instructions, just download raw source code)
- Copy source code directory to sublime packages directory. In mac it is here
  /users/[username]/library/Application Support/Sublime Text 3/Packages/
