### ISSUE TITLE
Stopping on invisible break point

### ISSUE THREAD

**Issue by LiquaFoo** [martomo/SublimeTextXdebug#99]
I have a bug where a break point is being hit that is not visibly set. There are no breakpoints listed in the break points list either. Attempted to reinstall the plug in but that didn't work. Cleared cookies on browser that also didn't work. Also attempted to switch port from 9000 to 9001. Not sure if this is an XDebug issue or and issue with the plug-in.

**Comment by pherris** [comment]
Thanks, worked for me too!

**Comment by LiquaFoo** [comment]
Worked for me also, Thanks!
